[package]
name = "ca"
version = "0.1.0"
authors = ["Shiwei Zhang <ylxdzsw@gmail.com>"]
edition = "2021"

[lib]
path = "ca.rs"
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true

[dependencies]
serde_json = "1"
