name: Build and deploy to pages
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "2.2.1"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
          targets: wasm32-unknown-unknown

      - name: Compile WASM
        run: cargo build --release -Z build-std=std,panic_abort --target wasm32-unknown-unknown

      - name: Build HTML
        run: deno run -A https://raw.githubusercontent.com/ylxdzsw/nattoppet/master/nattoppet.ts main.ymd > index.html

      - name: Release Version
        if: startsWith(github.ref, 'refs/tags/v')
        run: cp index.html ${GITHUB_REF#refs/tags/}.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: "."
